#include "sys.h"
#include "utils/RandomStream.h"
#include "utils/StreamHasher.h"
#include <iomanip>
#include "debug.h"

int main()
{
  Debug(NAMESPACE_DEBUG::init());

  size_t const test_case = 3;
  size_t const stream_size = utils::HasherStreamBuf::size_hash_pairs[test_case].size;

  utils::RandomStream random(stream_size, 'A', 'Z');
  std::string str;
  random >> str;

  ASSERT(str == "UGSYAKGANIHODONWMKTGGIXEGFSZUCLGUPYLINGBNSCXADZQHJMHHYQTSSBMCTLPCHQFFLZFWHVJYWMAJTNKAXCZRMTPNLVWMZXD"
                "LIDOTACPSUWWPYZWQPXMCXVDURDRVYQJIBHGCBCDQIYZFSROSFTTXDRAHPJHSWDXPUOZZNUSKDVIVGYLWTJQPVAEHISZXTDHDXUK"
                "NHXVNPVMIPVMGUDJADELRCZQJGEACRYUGJJYZFOSRCJHCYMNDKCEPMQOIYZUFUBJRHICRIUUATKKFSUDETUXODTISJACTPVFVBDJ"
                "YOPNCHXOCKPBJENLUANBBSCBJNFQHNGMPEISKPPYTGNCFQDDZPZUWCEZDIXMFVNOHJOSRITXZXUSJQAXOBJNWKYMVATEGUZKFYVG"
                "PGXNMUPWPGCCJKWPTBLLHYKORROWMPPUAIRMRONPZOOXBMWCPUCMAWFNBPNPFMHZYCQWDGLQGFBVWQHQFICRUAELUBVGUFANNARD"
                "GSIOFGXMVNJTJOFGMADLRQPQFZBAMEFIQFCFRNVNOYGUVJEQQOXZALVFHLLDWOUNVFMUDGFUKAWQVTUCOYWKPCEUVUURUHPNZEFH"
                "CHWWJKVODLMLDKYMIMEFVLIVRHZYZYAHSAXPMWLTSUMVHCGTYVCWONUYIVVXTNLJZZTPJRSMCUILRCVMERFDUBWBKVVLWTPSJUGI"
                "VQYCBMTHBWEIESHJTEQLABRAWYZAETBXXBTBBVYABIUKWDKGPCLUAZIGQQBKYOVJGMWZNUCIZPYQCWPQODWRXPYRWNGFBJFRRHND"
                "LKRYGCCWCWDBMTBKEXWRCCSRTHKHMUIOCXQFSWXMNNPWLZICLAYCFIZYRWVBPIWKJCMCPMYVCYLCDWHQJNVKZYRAHFTRWCNIJEED"
                "QTKOJWDFYMTJFFLKRRKLHDHXOFVXDPGWINFHIRQJERJWYRTIAFRGEFNVAOIMZUZXDOAIPRCPPYSQKXXEIHLIOCPBROGVJUJBYVAO");

  utils::StreamHasher hasher;
  utils::RandomStreamBuf random_streambuf(stream_size, 'A', 'Z');
  hasher << &random_streambuf;

  auto digest = hasher.digest();
  Dout(dc::notice, "digest = 0x" << std::hex << digest);
  ASSERT(digest == utils::HasherStreamBuf::size_hash_pairs[test_case].hash);
  Dout(dc::notice, "Success.");
}
